# Reference: https://github.com/airockchip/rknn-toolkit2/tree/master/rknn-toolkit2/docs
quantization:
  target_platform: rk3588
  quant_type: INT8
  optimization_level: 3
  input_size_list: [[1, 3, 640, 640]]
  mean_values: [[0, 0, 0]]
  std_values: [[255, 255, 255]]
  calibration_dataset_dir: /data/reference/calibration
  calibration_dataset_size: 100
  batch_size: 1
  do_quantization: true
  quantized_dtype: asymmetric_quantized-8
  quantized_algorithm: normal
  mixed_precision_fallback: true
  output_tensor_type: float32
  rknn_batch_size: 1
